version: "3"

services: 
    db:
        image: 'mongo'
        volumes:
            - ./mongo:/data/db
        environment:
            - MONGO_INITDB_DATABASE=expensetracker
            # - MONGO_INITDB_ROOT_USERNAME=admin
            # - MONGO_INITDB_ROOT_PASSWORD=password
        ports:
            - '27017:27017'